### PR TITLE
catch errors on PurlFinder#index_purls

### LINKED ISSUE #99: PurlFinder.index_purls should log rather than raise exceptions
See https://github.com/sul-dlss/purl-fetcher/blob/master/lib/purl_finder.rb#L88-L89

There should be a `rescue block` there that logs the exception and increments the `error` count.

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #99 This was causing an error on stage. Verified things work now.

### CODE REVIEW

File: lib/purl_finder.rb [hunk 1]
```diff
@@ -85,7 +85,11 @@ def index_purls(params={})
       druid = get_druid_from_file_path(line)
       if !druid.blank?
         IndexingLogger.info("indexing #{druid}")
-        result = Purl.save_from_public_xml(File.dirname(line)) # pass the directory of the file containing public
+        begin
+          result = Purl.save_from_public_xml(File.dirname(line)) # pass the directory of the file containing public
+        rescue => e
+          IndexingLogger.error("An error occurred while trying to save #{druid}.  \n#{e.message} \n#{e.backtrace.inspect}")
+        end
```
Comment (drh-stanford) [inline lib/purl_finder.rb]: @mejackreed @lmcglohon just to be clear, does `result` become `false` if the exception is thrown? it's not clear to me that `error` gets incremented when an exception is raised from just reading the code. It looks like the spec does verify that `error` is getting set. thoughts?

Comment (mejackreed) [inline lib/purl_finder.rb]: Hm.. I see what you are saving. Maybe set to false above?

Comment (drh-stanford) [inline lib/purl_finder.rb]: Or maybe it's better to change the `Purl.save_from_public_xml` to thrown an exception (which may just be changing `.save` to `.save!`?) rather than return `true` or `false`? Then we could write something like this:

```ruby
begin
  Purl.save_from_public_xml(...)
  success += 1
rescue => e
  IndexingLogger.error(...)
  error += 1
end
```

Comment (mejackreed) [inline lib/purl_finder.rb]: Yeah that seems better 👍
